// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenConquer.Infrastructure.Persistence.Game.Context;

#nullable disable

namespace OpenConquer.Infrastructure.Persistence.Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260914210346_InitialGameSchema")]
    partial class InitialGameSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_as_cs")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Game.CharacterRecord", b =>
                {
                    b.Property<uint>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("character_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("CharacterId"));

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<ushort>("Agility")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("agility");

                    b.Property<uint>("AppearanceComposite")
                        .HasColumnType("int unsigned")
                        .HasColumnName("appearance_composite");

                    b.Property<uint>("BoundConquerPoints")
                        .HasColumnType("int unsigned")
                        .HasColumnName("bound_conquer_points");

                    b.Property<uint>("ConquerPoints")
                        .HasColumnType("int unsigned")
                        .HasColumnName("conquer_points");

                    b.Property<ushort>("CurrentLife")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("current_life");

                    b.Property<ushort>("CurrentMana")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("current_mana");

                    b.Property<ushort>("EnlightenmentPoints")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("enlightenment_points");

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("experience");

                    b.Property<byte>("FirstProfession")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("first_profession");

                    b.Property<ushort>("HairComposite")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("hair_composite");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<uint>("MapId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<ushort>("PkPoints")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("pk_points");

                    b.Property<ushort>("PositionX")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("position_x");

                    b.Property<ushort>("PositionY")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("position_y");

                    b.Property<byte>("PreviousProfession")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("previous_profession");

                    b.Property<byte>("Profession")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("profession");

                    b.Property<byte>("RebirthCount")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("rebirth_count");

                    b.Property<uint>("Silver")
                        .HasColumnType("int unsigned")
                        .HasColumnName("silver");

                    b.Property<ushort>("Spirit")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("spirit");

                    b.Property<ushort>("Strength")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("strength");

                    b.Property<ushort>("TitleId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("title_id");

                    b.Property<ushort>("UnspentAttributePoints")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("unspent_attribute_points");

                    b.Property<ushort>("Vitality")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("vitality");

                    b.HasKey("CharacterId")
                        .HasName("PK_characters");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_characters_account_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_characters_name");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("CK_characters_account_id", "`account_id` > 0");

                            t.HasCheckConstraint("CK_characters_appearance_composite", "`appearance_composite` > 0");

                            t.HasCheckConstraint("CK_characters_level", "`level` BETWEEN 1 AND 140");

                            t.HasCheckConstraint("CK_characters_map_id", "`map_id` > 0");

                            t.HasCheckConstraint("CK_characters_name_length", "CHAR_LENGTH(`name`) BETWEEN 4 AND 15");

                            t.HasCheckConstraint("CK_characters_profession", "`profession` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_as_cs");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Schema.SchemaCompatibilityRecord", b =>
                {
                    b.Property<string>("ComponentName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("component_name")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ComponentName"), "ascii");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("migration_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MigrationId"), "ascii");

                    b.Property<uint>("SchemaVersion")
                        .HasColumnType("int unsigned")
                        .HasColumnName("schema_version");

                    b.HasKey("ComponentName")
                        .HasName("PK_schema_compatibility");

                    b.ToTable("schema_compatibility", null, t =>
                        {
                            t.HasCheckConstraint("CK_schema_compatibility_component_name", "CHAR_LENGTH(`component_name`) > 0");

                            t.HasCheckConstraint("CK_schema_compatibility_migration_id", "CHAR_LENGTH(`migration_id`) > 0");

                            t.HasCheckConstraint("CK_schema_compatibility_schema_version", "`schema_version` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "ascii");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "ascii_bin");
                });
#pragma warning restore 612, 618
        }
    }
}
