// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenConquer.Infrastructure.Persistence;

#nullable disable

namespace OpenConquer.Infrastructure.Persistence.Accounts.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_as_cs")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountAuditEventRecord", b =>
                {
                    b.Property<ulong>("AccountAuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("account_audit_event_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("AccountAuditEventId"));

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<uint?>("ActorAccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("actor_account_id");

                    b.Property<byte>("ActorKind")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("actor_kind");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("correlation_id");

                    b.Property<byte>("EventKind")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("event_kind");

                    b.Property<byte?>("NewAccessStatus")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("new_access_status");

                    b.Property<byte?>("NewAuthorityRole")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("new_authority_role");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<byte?>("PreviousAccessStatus")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("previous_access_status");

                    b.Property<byte?>("PreviousAuthorityRole")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("previous_authority_role");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("reason_code")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ReasonCode"), "ascii");

                    b.HasKey("AccountAuditEventId")
                        .HasName("PK_account_audit_events");

                    b.HasIndex("ActorAccountId")
                        .HasDatabaseName("IX_account_audit_events_actor_account_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_account_audit_events_correlation_id");

                    b.HasIndex("AccountId", "OccurredAtUtc")
                        .HasDatabaseName("IX_account_audit_events_account_id_occurred_at_utc");

                    b.ToTable("account_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_audit_events_actor", "((`event_kind` = 1 AND `actor_kind` = 1 AND `actor_account_id` IS NULL) OR (`actor_kind` = 2 AND `actor_account_id` IS NOT NULL) OR (`actor_kind` IN (3, 4) AND `actor_account_id` IS NULL))");

                            t.HasCheckConstraint("CK_account_audit_events_correlation_id", "`correlation_id` <> 0x00000000000000000000000000000000");

                            t.HasCheckConstraint("CK_account_audit_events_event_kind", "`event_kind` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)");

                            t.HasCheckConstraint("CK_account_audit_events_new_access_status", "`new_access_status` IS NULL OR `new_access_status` IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_account_audit_events_new_authority_role", "`new_authority_role` IS NULL OR `new_authority_role` IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_account_audit_events_payload", "((`event_kind` = 1 AND `previous_access_status` IS NULL AND `new_access_status` IS NOT NULL AND `new_access_status` IN (1, 2, 3) AND `previous_authority_role` IS NULL AND `new_authority_role` IS NOT NULL AND `new_authority_role` IN (1, 2, 3, 4, 5)) OR (`event_kind` = 2 AND `previous_access_status` IS NOT NULL AND `previous_access_status` = 1 AND `new_access_status` IS NOT NULL AND `new_access_status` = 2 AND `previous_authority_role` IS NULL AND `new_authority_role` IS NULL) OR (`event_kind` = 3 AND `previous_access_status` IS NOT NULL AND `previous_access_status` = 2 AND `new_access_status` IS NOT NULL AND `new_access_status` = 1 AND `previous_authority_role` IS NULL AND `new_authority_role` IS NULL) OR (`event_kind` = 4 AND `previous_access_status` IS NOT NULL AND `previous_access_status` IN (1, 2) AND `new_access_status` IS NOT NULL AND `new_access_status` = 3 AND `previous_authority_role` IS NULL AND `new_authority_role` IS NULL) OR (`event_kind` = 5 AND `previous_access_status` IS NOT NULL AND `previous_access_status` = 3 AND `new_access_status` IS NOT NULL AND `new_access_status` IN (1, 2) AND `previous_authority_role` IS NULL AND `new_authority_role` IS NULL) OR (`event_kind` IN (6, 7, 8, 9) AND `previous_access_status` IS NULL AND `new_access_status` IS NULL AND `previous_authority_role` IS NULL AND `new_authority_role` IS NULL) OR (`event_kind` = 10 AND `previous_access_status` IS NULL AND `new_access_status` IS NULL AND `previous_authority_role` IS NOT NULL AND `previous_authority_role` IN (1, 2, 3, 4, 5) AND `new_authority_role` IS NOT NULL AND `new_authority_role` IN (1, 2, 3, 4, 5) AND `previous_authority_role` <> `new_authority_role`))");

                            t.HasCheckConstraint("CK_account_audit_events_previous_access_status", "`previous_access_status` IS NULL OR `previous_access_status` IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_account_audit_events_previous_authority_role", "`previous_authority_role` IS NULL OR `previous_authority_role` IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_account_audit_events_reason_code", "`reason_code` IS NULL OR CHAR_LENGTH(`reason_code`) > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_as_cs");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountPasswordCredentialRecord", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash")
                        .UseCollation("utf8mb4_0900_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PasswordHash"), "utf8mb4");

                    b.Property<ulong>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("revision");

                    b.HasKey("AccountId")
                        .HasName("PK_account_password_credentials");

                    b.ToTable("account_password_credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_password_credentials_password_hash", "CHAR_LENGTH(`password_hash`) > 0");

                            t.HasCheckConstraint("CK_account_password_credentials_revision", "`revision` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_as_cs");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("AccountId"));

                    b.Property<byte>("AccessStatus")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("access_status");

                    b.Property<byte>("AuthorityRole")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("authority_role");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<uint?>("CreatedByAccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("created_by_account_id");

                    b.Property<byte>("CreatedByActorKind")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("created_by_actor_kind");

                    b.Property<Guid>("CreationOperationId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("creation_operation_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at_utc");

                    b.Property<uint?>("DeletedByAccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("deleted_by_account_id");

                    b.Property<byte?>("DeletedByActorKind")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("deleted_by_actor_kind");

                    b.Property<DateTime?>("LastSuccessfulLoginAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_successful_login_at_utc");

                    b.Property<DateTime>("StateChangedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("state_changed_at_utc");

                    b.Property<uint?>("StateChangedByAccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("state_changed_by_account_id");

                    b.Property<byte>("StateChangedByActorKind")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("state_changed_by_actor_kind");

                    b.Property<ulong>("StateRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("state_revision");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Username"), "utf8mb4");

                    b.HasKey("AccountId")
                        .HasName("PK_accounts");

                    b.HasIndex("CreatedByAccountId")
                        .HasDatabaseName("IX_accounts_created_by_account_id");

                    b.HasIndex("CreationOperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_accounts_creation_operation_id");

                    b.HasIndex("DeletedByAccountId")
                        .HasDatabaseName("IX_accounts_deleted_by_account_id");

                    b.HasIndex("StateChangedByAccountId")
                        .HasDatabaseName("IX_accounts_state_changed_by_account_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_accounts_username");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_accounts_access_status", "`access_status` IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_accounts_authority_role", "`authority_role` IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_accounts_created_actor", "((`created_by_actor_kind` = 2 AND `created_by_account_id` IS NOT NULL) OR (`created_by_actor_kind` IN (1, 3, 4) AND `created_by_account_id` IS NULL))");

                            t.HasCheckConstraint("CK_accounts_creation_operation_id", "`creation_operation_id` <> 0x00000000000000000000000000000000");

                            t.HasCheckConstraint("CK_accounts_deleted_state", "((`deleted_at_utc` IS NULL AND `deleted_by_actor_kind` IS NULL AND `deleted_by_account_id` IS NULL) OR (`deleted_at_utc` IS NOT NULL AND `deleted_at_utc` = `state_changed_at_utc` AND `deleted_by_actor_kind` IS NOT NULL AND `deleted_by_actor_kind` = `state_changed_by_actor_kind` AND (`deleted_by_account_id` <=> `state_changed_by_account_id`) AND ((`deleted_by_actor_kind` = 2 AND `deleted_by_account_id` IS NOT NULL) OR (`deleted_by_actor_kind` IN (3, 4) AND `deleted_by_account_id` IS NULL))))");

                            t.HasCheckConstraint("CK_accounts_last_successful_login_at", "`last_successful_login_at_utc` IS NULL OR `last_successful_login_at_utc` >= `created_at_utc`");

                            t.HasCheckConstraint("CK_accounts_state_changed_actor", "((`state_changed_by_actor_kind` = 2 AND `state_changed_by_account_id` IS NOT NULL) OR (`state_changed_by_actor_kind` IN (3, 4) AND `state_changed_by_account_id` IS NULL))");

                            t.HasCheckConstraint("CK_accounts_state_changed_at", "`state_changed_at_utc` >= `created_at_utc`");

                            t.HasCheckConstraint("CK_accounts_state_revision", "`state_revision` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_as_cs");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.GameLoginTicketRecord", b =>
                {
                    b.Property<uint>("SessionUid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("session_uid");

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<uint>("AuthenticationKey")
                        .HasColumnType("int unsigned")
                        .HasColumnName("authentication_key");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Username"), "utf8mb4");

                    b.HasKey("SessionUid")
                        .HasName("PK_game_login_tickets");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_game_login_tickets_account_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_game_login_tickets_expires_at_utc");

                    b.ToTable("game_login_tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_login_tickets_expiration", "`expires_at_utc` > `issued_at_utc`");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_0900_as_cs");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.SchemaCompatibilityRecord", b =>
                {
                    b.Property<string>("ComponentName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("component_name")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ComponentName"), "ascii");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("migration_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MigrationId"), "ascii");

                    b.Property<uint>("SchemaVersion")
                        .HasColumnType("int unsigned")
                        .HasColumnName("schema_version");

                    b.HasKey("ComponentName")
                        .HasName("PK_schema_compatibility");

                    b.ToTable("schema_compatibility", null, t =>
                        {
                            t.HasCheckConstraint("CK_schema_compatibility_component_name", "CHAR_LENGTH(`component_name`) > 0");

                            t.HasCheckConstraint("CK_schema_compatibility_migration_id", "CHAR_LENGTH(`migration_id`) > 0");

                            t.HasCheckConstraint("CK_schema_compatibility_schema_version", "`schema_version` > 0");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "ascii");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "ascii_bin");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountAuditEventRecord", b =>
                {
                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_account_audit_events_account");

                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_account_audit_events_actor_account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountPasswordCredentialRecord", b =>
                {
                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", "Account")
                        .WithOne("PasswordCredential")
                        .HasForeignKey("OpenConquer.Infrastructure.Persistence.Accounts.AccountPasswordCredentialRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_account_password_credentials_account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", b =>
                {
                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_accounts_created_by_account");

                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("DeletedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_accounts_deleted_by_account");

                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("StateChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_accounts_state_changed_by_account");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.GameLoginTicketRecord", b =>
                {
                    b.HasOne("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_game_login_tickets_account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenConquer.Infrastructure.Persistence.Accounts.AccountRecord", b =>
                {
                    b.Navigation("PasswordCredential")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
